services:
    kernel.listener.user_listener:
        class: Dan\UserBundle\EventListener\UserListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, connection: default }