services:
    dan_main.plugin_manager:
        class: Dan\MainBundle\Plugin\PluginManager
        calls:
            - [setLogger, [@logger]]

    model.manager.metadata:
        class: Dan\MainBundle\Model\MetadataManager
        arguments:
            - @doctrine.orm.entity_manager
