imports:
    - { resource: services/event_listener.yml }
    - { resource: services/form_type.yml }

parameters:
#    dan_user.example.class: Dan\UserBundle\Example
    oauth.user_provider.class: Dan\UserBundle\Security\FOSUBUserProvider
    dan_user.images_dir: /files/images/users

services:
    oauth.user_provider:
        class: "%oauth.user_provider.class%"
        arguments: 
            - @fos_user.user_manager
            - {google: googleId, facebook: facebookId}
        calls:
            - [ setLogger, [ @logger ]]

#    fos_google.user_provider:
#        class: Dan\UserBundle\Security\GoogleProvider
#        arguments:
#            google: @fos_google.api
#            userManager: @fos_user.user_manager
#            validator: @validator
#            em: @doctrine.orm.entity_manager
#            kernel: @kernel

    model.manager.user:
        class: Dan\UserBundle\Model\UserManager
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @fos_user.entity_manager
            - %fos_user.model.user.class%
        calls:
            - [setKernel,[@kernel]]
            - [setImageDir,[%dan_user.images_dir%]]
            - [setUserMetadataManager,[@model.manager.user_metadata]]

    model.manager.user_metadata:
        class: Dan\UserBundle\Model\UserMetadataManager
        arguments:
            - @doctrine.orm.entity_manager

    dan_user.twig.image_extension:
        class: Dan\UserBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }
